apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: output
    description: The git repo will be cloned into this workspace
  params:
  - name: url
    description: git url to clone
    type: string
  - name: revision
    description: git revision to checkout (branch, tag, sha, ref…)
    type: string
    default: main
  steps:
  - name: clone
    image: alpine/git:v2.26.2
    script: |
      git clone $(params.url) /workspace/output/
      cd /workspace/output/
      git checkout $(params.revision)