version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Budgy_production
      POSTGRES_USER: Budgy
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./log:/app/log
      - ./tmp:/app/tmp
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      DATABASE_URL: postgres://Budgy:password@db:5432/Budgy_production
      SECRET_KEY_BASE: d4781f78b7340553ad40d5bb40179590bfd6e95e6ea58890e96915983e5b9cc6a3d0639df3144c0fff0ddd9b9facf59ac3822413e67f3ef42afb80e3568d5398

volumes:
  pgdata: