apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: budget-app-cluster
spec:
  location: us-central1-a
  initialNodeCount: 2
  nodeConfig:
    machineType: e2-standard-2
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  networkingMode: VPC_NATIVE
  releaseChannel:
    channel: REGULAR