# git-resource.yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/HEMAAAAA/Ruby-App.git
    - name: revision
      value: main  # Or the branch you wish to use
  secrets:
    - fieldName: authSecret
      secretName: github-credentials
      secretKey: password