apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-commit-push
spec:
  params:
    - name: message
      description: The commit message
      default: "Update image tag in manifests"
  workspaces:
    - name: source
  steps:
    - name: git-commit
      image: alpine/git:latest
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.source.path)
        git config --global user.email "tekton@example.com"
        git config --global user.name "Tekton Pipeline"
        git add .
        git commit -m "$(params.message)"
        git push