apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifests
spec:
  params:
    - name: image-name
      description: The image name including registry
    - name: image-tag
      description: The new image tag
    - name: manifest-path
      description: Path to the manifests to update
  workspaces:
    - name: source
  steps:
    - name: update-image
      image: bitnami/kubectl:latest
      script: |
        #!/usr/bin/env bash
        cd $(workspaces.source.path)/$(params.manifest-path)
        sed -i "s|$(params.image-name):.*|$(params.image-name):$(params.image-tag)|g" deployment.yaml
        echo "Updated image to $(params.image-name):$(params.image-tag)"