# pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: IMAGE
    - name: IMAGE_TAG
      description: The image tag to use
      default: latest
    - name: MANIFEST_PATH
      description: Path to Kubernetes manifests
      default: k8s
  workspaces:
    - name: shared-workspace
  resources:
    - name: git-repo
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: clone-git-repo
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      resources:
        outputs:
          - name: source
            resource: git-repo
      params:
        - name: url
          value: $(resources.git-repo.url)
        - name: revision
          value: main

    - name: build-and-push-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - clone-git-repo
      workspaces:
        - name: source
          workspace: shared-workspace
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: docker-image
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)

    - name: update-k8s-manifests
      taskRef:
        name: update-manifests
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: docker.io/hema995/budgetapp
        - name: image-tag
          value: $(params.IMAGE_TAG)
        - name: manifest-path
          value: $(params.MANIFEST_PATH)
