apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: budget-app-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: Git repository URL
  - name: git-revision
    type: string
    description: Git revision to build
    default: main
  - name: image-name
    type: string
    description: Image name including registry
    default: hema995/budgetapp
  - name: image-tag
    type: string
    description: Image tag
    default: latest
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
  - name: run-tests
    taskRef:
      name: ruby-test
    runAfter:
    - fetch-source
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: build-image
    taskRef:
      name: kaniko
    runAfter:
    - run-tests
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.image-name):$(params.image-tag)
  - name: update-manifest
    taskRef:
      name: update-deployment
    runAfter:
    - build-image
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image
      value: $(params.image-name):$(params.image-tag)
    - name: path
      value: kubernetes/deployment.yaml