# pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-pipeline-run-
spec:
  serviceAccountName: tekton-pipeline-sa
  pipelineRef:
    name: ci-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
  resources:
    - name: git-repo
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image
  params:
    - name: IMAGE
      value: docker.io/hema995/budgetapp
    - name: IMAGE_TAG
      value: $(context.pipelineRun.uid)
    - name: MANIFEST_PATH
      value: k8s
