apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: budget-app-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: budget-app-pipeline-run-
      spec:
        serviceAccountName: tekton-pipeline-sa
        pipelineRef:
          name: ci-pipeline
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace-pvc
        resources:
          - name: git-repo
            resourceRef:
              name: git-source
          - name: docker-image
            resourceRef:
              name: docker-image
        params:
          - name: IMAGE
            value: docker.io/hema995/budgetapp
          - name: IMAGE_TAG
            value: $(uid)
          - name: MANIFEST_PATH
            value: kubernetes
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: budget-app-trigger-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: budget-app-event-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: budget-app-trigger-binding
      template:
        ref: budget-app-trigger-template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
secrets:
  - name: github-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-role