apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
    username: ArgoCD
    icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} has been deployed.
      Revision: {{.app.status.sync.revision}}
  template.app-health-degraded: |
    message: |
      Application {{.app.metadata.name}} has degraded.
      {{if eq .serviceType "slack"}}
      <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|Open in ArgoCD>
      {{end}}
  trigger.on-deployed: |
    - description: Application is synced and healthy
      oncePer: app.status.sync.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'