apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/HEMAAAAA/Ruby-App.git
  username: HEMAAAAA
  password: <github_pat_token>
