apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/HEMAAAAA/Budget-App.git
  username: HEMAAAAA
  password: <your-github-token>  # Replace with your actual GitHub token or password