apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  url: postgres://Budgy:password@postgres-service:5432/Budgy_production
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  secret-key-base: d4781f78b7340553ad40d5bb40179590bfd6e95e6ea58890e96915983e5b9cc6a3d0639df3144c0fff0ddd9b9facf59ac3822413e67f3ef42afb80e3568d5398